go.mod
storage/gcp/gcp.go
storage/gcp/gcp_test.go

This PR adds Spanner support to the GCP storage implementation, along with sequencing support.
TODO: relies on #44, merge & rebase.
Towards #23

Add outline of GCP spanner implementation

---

storage/gcp/gcp.go
storage/gcp/gcp_test.go

This PR adds support for getting sequenced entries back from the sequencer portion of the GCP implementation, and is a precursor for adding the integration support.
Toward #23

Consume previously sequenced entries

---

go.mod
go.sum
storage/integrate.go
storage/integrate_test.go
storage/tileid.go

This PR adds a storage mix-in for performing the integration of new entries into the log.
Towards #6 & #23

Add integrate mix-in

---

storage/gcp/gcp.go
storage/gcp/gcp_test.go
storage/integrate.go
storage/integrate_test.go

This PR pulls in the integrate mix-in from #61 and uses it in the GCP storage.
Towards #23

Add support for integration in GCP storage

---

cmd/example-gcp/main.go
go.mod
go.sum
log.go
storage/gcp/gcp.go

This PR adds two common storage options:
- one for setting a signer to be used when signing checkpoints
- one for configuring the batching queue.

Add Checkpoint option & batch options

---

storage/integrate.go

This PR detects when the cache is requesting tiles which are beyond the extent of the current tree and skips the read.
These "future" tiles are very likely not to exist, and, since they're requested by the visitor, we end up trying to fetching serially which adds a fair chunk of latency to an integration run. Not fetching these future tiles speeds the integration up by around 25%. 
While it's possible that these tiles could occasionally exist (e.g. due to an integration run crashing previously), not reading should still be safe as the storage design makes integration an idempotent operation, and this is enforced when tiles are finally flushed to GCS at the end of the integration run.
Toward #23

GCP: Don't try to read tiles which very probably don't exist

---

cmd/example-gcp/main.go
storage/gcp/gcp.go

This PR allows an easy way for the hammer to get access to the log static resources by proxying read requests into GCS reads.

GCP: temporary hack to proxy read requests to GCS

---

storage/gcp/gcp.go
storage/queue.go
storage/queue_test.go

This PR reintroduces a single-threaded nature for queue flushing.
Given the strictly serialised nature of assigning sequence numbers without gaps it's unlikely that storage implementations would be able to increase performance by taking multiple flushes in parallel.
Toward #6

Reintroduce sync for flushing

---

client/client_test.go
cmd/example-posix/main.go
storage/posix/files.go
storage/posix/integrate.go
storage/posix/writer.go
testdata/build_log.sh

This is largely a copy and paste job from both the experimental Betty repo and from serverless. The primary motivation to have this posix implementation right now is to generate test data, such as that used in #49.
There has been little in the way of optimization. The primary concern was minimal code changes in order to get a working posix log to generate test data.
Towards #22

Posix log implementation of tlog-tiles

---

api/state.go
api/state_test.go
ct_only.go
ctonly/ct.go
entry.go
entry_test.go
storage/gcp/gcp.go
storage/gcp/gcp_test.go
storage/integrate.go
storage/integrate_test.go
storage/queue.go
storage/queue_test.go

This PR enables Tessera to support a [CT Static API](https://c2sp.org/ct-static-api) personality.
There's broadly two things which are necessary to be able to support that personality:
1. Formatting of `EntryBundle` is different and incompatible
[tlog-tiles](https://c2sp.org/tlog-tiles) specifies a `length/value` scheme, whereas CT Static API specifies just `value` and relies on the fact that `value` in this case is self-describing.
2. Each log entry _contains its own index in the log_.
The SCT returned to the submitter contains the sequence number of the entry in the log in the `CtExtensions` field of the SCT struct. What's not obvious from the spec is that this must also be part of the Merkle leaf (otherwise compatibility with RFC6962 would be broken).
This means that we don't actually …

CT static API support

---

cmd/example-mysql/main.go
go.mod
storage/mysql/mysql.go

Improve `writeCheckpoint` in MySQL storage implementation

---

cmd/example-gcp/main.go
cmd/example-mysql/main.go
log.go

Add `WithCheckpointVerifier` to `tessera.StorageOptions` for parsing checkpoints

---

deployment/README.md
deployment/live/example-gcp/README.md
deployment/live/example-gcp/terragrunt.hcl
deployment/modules/gcs/main.tf

This PR also changes the base name from "example-gcp" to "trillian-tessera" since I think it makes more sense as a default value. I'd rather fix this sooner rather than later, but happy to revert this change if you think it's too disruptive.

Complete instructions to deploy Tessera GCP

---

cmd/example-mysql/main.go
storage/mysql/mysql.go

Add sequence and integrate foundation to MySQL storage implementation

---

cmd/example-gcp/main.go
log.go
storage/gcp/gcp.go

This PR enables support of `WithBatching` in the GCP storage.
Toward #23

Support WithBatching in GCP

---

storage/queue.go

This PR corrects the assertion that storage must have called `MarshalBundleData` to avoid triggering if there was some earlier unrelated error.

Fix check for broken storage

---

storage/mysql/mysql.go

Add sequenced entries to entry bundles in MySQL storage implementation

---

storage/mysql/mysql.go

Optimize hash tiles fetch in MySQL storage implementation

---

storage/mysql/mysql.go

Fix sequence and integrate in MySQL storage implementation

---

.github/workflows/go_test.yml
storage/mysql/mysql_test.go

#21 
The Go test can successfully connect to the GitHub workflow's MySQL test database.
```
Run go test -v -race ./storage/mysql/...
go: downloading go1.22.5 (linux/amd64)
go: downloading github.com/go-sql-driver/mysql v1.[8](https://github.com/transparency-dev/trillian-tessera/actions/runs/10197078592/job/28209161789#step:4:9).1
go: downloading github.com/transparency-dev/merkle v0.0.2
go: downloading k8s.io/klog/v2 v2.130.1
go: downloading github.com/transparency-dev/formats v0.0.0-20240715203801-[9](https://github.com/transparency-dev/trillian-tessera/actions/runs/10197078592/job/28209161789#step:4:10)ff9b9e3905f
go: downloading golang.org/x/mod v0.19.0
go: downloading github.com/globocom/go-buffer v1.2.2
go: downloading golang.org/x/exp v0.0.0-20220827204233-334a2380cb91
go: …
```

Add MySQL Go test to GitHub workflows

---

.github/workflows/go_test.yml
storage/mysql/mysql_test.go

#21 
```sh
Run go test -v -race ./storage/mysql/... -is_mysql_test_optional=false
go test -v -race ./storage/mysql/... -is_mysql_test_optional=false
shell: /usr/bin/bash -e {0}
env:
DB_DATABASE: test_tessera
DB_USER: root
DB_PASSWORD: root
go: downloading go1.22.5 (linux/amd64)
go: downloading github.com/go-sql-driver/mysql v1.8.1
go: downloading github.com/transparency-dev/merkle v0.0.2
go: downloading k8s.io/klog/v2 v2.130.1
go: downloading github.com/transparency-dev/formats v0.0.0-20240715203801-9ff9b9e3905f
go: downloading golang.org/x/mod v0.19.0
go: downloading github.com/globocom/go-buffer v1.2.2
go: downloading golang.org/x/exp v0.0.0-20220827204233-334a2380cb91
go: downloading golang.org/x/crypto v0.25.0
go: downloading filippo.io/edwards25519 v1.1.0
go: downloading …
```

Force MySQL Go test to fail on GitHub workflow if the MySQL test database is not available

---

go.mod
go.sum
hammer/hammer.go
hammer/workers.go

this PR adds a few (hopefully) useful stats lines to the top pane: 
- checkpoint size & growth-per-second averaged over the last 30s,
- a "sampled" min-avg-max of how long entries wait to have indices assigned (i.e. `Add()` latency)
- a "sampled" total-time-to-integrate (i.e latency from calling `Add()` to a checkpoint committing to the entry.
```
│Read: Current max: 10/s. Oversupply in last second: 0
│Write: Current max: 10000/s. Oversupply in last second: 1018
│TreeSize: 179489419 (Δ 957qps over 30s)
│Time-in-queue: 981ms/1863ms/3031ms (min/avg/max)
│Total-time-to-integrate: 1399ms/2432ms/4055ms (min/avg/max)
```

Hammer stats

---

hammer/client.go
hammer/hammer.go
hammer/workers.go

This PR adds support in the hammer for recognising and reacting to pushback from the target log.

Hammer pushback support

---

cmd/example-gcp/main.go
storage/gcp/gcp.go

This PR adjusts behaviour of the GCP storage implementation slightly to improve performance, and avoid having to redo work due to GCS update limits.
#23

Performance tweaks for GCP

---

storage/gcp/gcp.go

This PR corrects a bug introduced in #109 which causes the GCP integration loop to exit if there's an error during an integration run.

Don't break integration on error

---

storage/mysql/mysql.go
storage/mysql/mysql_test.go

#21 
Note that this pull request also makes `tessera.WithCheckpointSignerVerifier` optional in `mysql.New()` because the issue was found during the tests development.

Add Go tests in MySQL storage implementation

---

personalities/sctfe/structures_test.go
personalities/sctfe/testdata/keys.go

This PR:
- copies over trillian/testdata/keys.go
- updates import paths to point at the local repo instead

drop dependency on c-t-go/testdata

---

personalities/sctfe/handlers.go
personalities/sctfe/handlers_test.go
personalities/sctfe/instance.go
personalities/sctfe/timesource.go
personalities/sctfe/timesource_export_test.go

I don't see any reason why it would be in its own package. Packages named util are discouraged, https://go.dev/blog/package-names#bad-package-names, let's get rid of it.

move c-t-go/util/timesource.go to sctfe package

---

personalities/sctfe/cert_checker_test.go
personalities/sctfe/cert_quota_test.go
personalities/sctfe/handlers_test.go
personalities/sctfe/serialize_test.go
personalities/sctfe/testdata/certificates.go

#88 
This PR moves c-t-go/trillian/ctfe/testonly/certificates.go to testdata/, and updates imports accordingly.

Drop dependency on c-t-go/trillian/ctfe/testonly

---

go.mod
go.sum
personalities/sctfe/ct_server_gcp/main.go
personalities/sctfe/instance.go
personalities/sctfe/instance_test.go

This was added to the CTFE to cache individual certs in the issuance chain. We don't need this anymore since the SCTFE won't serve issuance chain certs anymore, at least not with bucket styled storage system.

Remove issuance chain cache

---

personalities/sctfe/ct_server_gcp/main.go
personalities/sctfe/handlers.go
personalities/sctfe/handlers_test.go
personalities/sctfe/instance.go
personalities/sctfe/instance_test.go
personalities/sctfe/serialize.go

This PR makes it possible to sign https://c2sp.org/static-ct-api checkpoints, and passes a signer to Tessera.
Before we can pass a Checkpoint signer to Tessera, we need to initiate the time source and crypto.signer, so I had to re-architecture the code a bit before that.

Pass a signer to Tessera

---

ctonly/ct.go
personalities/sctfe/handlers.go
personalities/sctfe/handlers_test.go

https://github.com/transparency-dev/trillian-tessera/issues/88
See specs here: https://github.com/C2SP/C2SP/blob/main/static-ct-api.md#log-entries, the issuer fingerprints are be at the end of a leaf.
I also had to fix `TestAddChainWhitespace`, and took that as an opportunity to abstract some testing function.

Add FingerprintsChain to leaf data

---

.github/workflows/integration_test.yml
cmd/example-mysql/main.go
integration/example-mysql/integration_test.go

#8 #21 
This PR not only add the MySQL tlog tiles API integration test but also fixes the read entry bundle API bug in example-mysql.

Add MySQL tlog tiles API integration test

---

cmd/example-mysql/main.go
storage/mysql/mysql.go

Fix incorrect http status not found behaviour in MySQL storage

---

hammer/hammer.go
hammer/tui.go

Separating the experimentation from the measurement makes it easier to understand the code and avoid the hammer growing into a monolith.

Split the analysis out of the hammer

---

hammer/hammer.go
hammer/hammer_test.go
hammer/tui.go

Basic tests to make sure that the average reported is correct and that
async behaviour is reliable.

Tests for the hammer analysis

---

hammer/README.md

The previous version had a smaller number of writers than operations to perform, which meant it was often blocked until a batch was flushed. This updates the sample command to values that leave the hammer always performing work instead of blocking.

Better sample command for hammer

---

deployment/modules/gcs/outputs.tf

Any code using this will need the name of the writer service account in order to run the writing code as the service account.

GCS terraform: output the writer service account

---

hammer/README.md
hammer/hammer.go

The hammer can be configured to stop successfully if a desired number of leaves are written, and to fail after a max runtime is reached. These two can be used in conjunction to run a headless test for write performance.

Hammer: exit criteria

---

storage/gcp/gcp.go
storage/gcp/gcp_test.go

If not specified, GCS automatically detects the content type, so let's be explicit and avoid unfortunate divergence outside of our control.
I haven't added tests, but since there was some divergence before https://github.com/C2SP/C2SP/pull/92, it proves that it can happen, and doesn't sound crazy to add some. I can do this in a later PR but we'd also need to modify the getObject signature, which sounds a bit cumbersome.

Explicitly Set content types on tiles and leaves

---

.github/workflows/benchmark_mysql.yml

This ensures a basic level of write performance. It isn't a perfect performance benchmark because the job could be run on different specs of machine, but it's a first foray into getting the hammer running in CI.

Run hammer against MySQL in CI

---

cmd/example-gcp/Dockerfile

This PR adds a simple Dockerfile for building the `example-gcp` binary.
Eventually, this can be used for CI/CD testing on GCP.
Towards #7.

Add Dockerfile for example-gcp

---

AUTHORS
README.md

Fixes broken link to the [CT-Tiles] api spec document that was renamed.

Fix broken link in README.md

---

storage/gcp/gcp.go

Need to initialize the writer before setting the content type

Set content type appropriately

---

storage/gcp/gcp.go

This PR stops the GCP storage implementation from scanning all the buckets at startup.
It did this to try to provide an early/helpful error message, but doing this requires extra IAM permissions which are completely unnecessary for running the log, and so should not be granted.
In reality the log instance will detect the missing bucket and start erroring out as soon as writes are attempted anyway.

GCP: Don't scan buckets

---

deployment/live/gcp/example-gcp/README.md
deployment/live/gcp/example-gcp/ci/terragrunt.hcl
deployment/live/gcp/example-gcp/terragrunt.hcl
deployment/modules/gcp/example-gcp/main.tf
deployment/modules/gcp/example-gcp/variables.tf
deployment/modules/gcp/gcs/main.tf
deployment/modules/gcp/gcs/outputs.tf

This PR adds support for spinning up an instance of the example personality on GCP.
This is intended to be used for CI tests.
Towards #7

Terraform for GCP CI base

---

go.mod

For no good reason this was split into multiple require blocks for the indirect deps. Unified these blocks back together and ran go mod tidy.

Tidied the go mod file

---

README.md

We can come back and add example usage in this main README if that's useful, but for now pointing to the examples that are fleshed out and are known to compile is a pragmatic step forward. It also gives newcomers links to binaries they can run to understand what Tessera can do, before they start writing any code.

README: direct users to the examples

---

personalities/sctfe/ct_server_gcp/main.go
personalities/sctfe/handlers.go
personalities/sctfe/handlers_test.go
personalities/sctfe/mockstorage/mock_ct_storage.go
personalities/sctfe/storage.go
personalities/sctfe/storage/gcp/issuers.go
personalities/sctfe/storage/gcp/map.go
storage/gcp/gcp.go

Store issuer chains

---

personalities/sctfe/storage.go
personalities/sctfe/storage/gcp/issuers.go

#88 
- Inline calls to Exists and simplify the API
- Write directly doing a read first: we're talking about saving cents here for 15k entries, it's not worth the complexity
-  crack open the precondition errors to make sure it's really failing because of the precondition we pass

Simplify issuer storage 

---

integration/storage_uniformity_test.go

This is a basic check that they support the same contract for Add. More methods can be added later.

Ensure that storage implementations meet the same contract

---

.github/workflows/go_test.yml

It makes noise on every PR and makes no real contribution so removing it until we have enough need to warrant setting this up properly.

Remove CodeCov for now

---

.github/workflows/go_test.yml

There are warnings complaining "Restore cache failed: Dependencies file is not found in /home/runner/work/trillian-tessera/trillian-tessera. Supported file pattern: go.sum". This is caused by setting up Go repository without checking out the source code.

Fix GH action warning by swapping checkout and setup-go

---

cmd/posix-oneshot/README.md
cmd/posix-oneshot/main.go
testdata/build_log.sh

The next step will be to turn the example-posix into a long-lived server that has an HTTP /add method to push new contents into the log.

Copy example-posix to posix-oneshot and document it

---

log.go
storage/gcp/gcp.go
storage/mysql/mysql.go
storage/posix/files.go

This PR removes the default options param from `ResolveStorageOptions`.
This is an unnecessary source of complexity at the moment.

Remove default options from ResolveStorageOptions

---

api/layout/paths.go
api/layout/paths_test.go
ct_only.go
ct_only_test.go
log.go
storage/gcp/gcp.go
storage/gcp/gcp_test.go
storage/posix/files.go

This PR adds support to Tessera for storing CT entry bundles in under `data`.
The [Static CT API](https://c2sp.org/static-ct-api) defines leaf entry bundles as being stored under a `tiles/data` path. This is incompatible with the [tlog-tiles spec](https://c2sp.org/tlog-tiles) which defines that path as `tiles/entries`.
This PR adds a CT-only storage option, `WithCTLayout`, which instructs storage implementations to use the Static CT API path.
A strong goal of this PR was to make it impossible for users of Tessera to implement arbitrary layout schemes, or accidentally use the CT layout without a clear signal that this is what they are doing. 
Fixes #171

Add support for Static CT API entry bundle paths

---

storage/posix/files.go

This PR fixes an error in the partial tile clean up code.
Previously the code expected to find partial tiles named as `<tileID>.<size>`, but the `tlog-tiles` spec requires partial tiles to be stored in a directory named `<tileID>.p/`. This resulted in errors like the one below when the storage implementation completed a full tile:
```
E0830 11:39:00.756914  239314 files.go:225] Integrate failed: failed to set tile({0 0}): failed to rename temp link over partial tile: rename /tmp/mylog/tile/0/000.link /tmp/mylog/tile/0/000.p: file exists
```
This PR fixes the incorrect path assumption.

Fix partial tile clean up

---

personalities/sctfe/ct_server_gcp/main.go

Will store entries under `tile/data` instead of `tile/entries`, see #171.
Toward #88

Enable WithCTLayout

---

cmd/example-gcp/main.go
cmd/example-mysql/main.go
cmd/example-posix/main.go
cmd/posix-oneshot/main.go
ct_only.go
integration/storage_uniformity_test.go
log.go
personalities/sctfe/handlers.go
personalities/sctfe/handlers_test.go
personalities/sctfe/mockstorage/mock_ct_storage.go
personalities/sctfe/storage.go
storage/gcp/gcp.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go
storage/posix/files.go
storage/queue.go
storage/queue_test.go

This PR returns the futures already present within calls to `Add()`, rather than blocking the caller directly. This allows the user of Tessera to decide what is best for them.
For HTTP-based services, a blocking call to `Add` isn't really an issue - there's generally a goroutine per request anyway, but for other use-cases having to artificially spin out a bunch of goroutines which call `Add` only to then need to join them again immediately afterwards is a bit weird. This PR solves that by allowing the caller of the `Add` method to choose _when_ to resolve the future.
The POSIX example/one-shot is a good example of the complexity this pushes onto users. Exposing the future removes a lot of that, although adds some (but arguably less) complexity of its own.

Surface futures from Add()

---

go.mod
go.sum
personalities/sctfe/ct_server_gcp/main.go
personalities/sctfe/handlers.go
personalities/sctfe/handlers_test.go
personalities/sctfe/mockstorage/mock_ct_storage.go
personalities/sctfe/modules/README.md
personalities/sctfe/modules/dedup/dedup.go
personalities/sctfe/serialize.go
personalities/sctfe/storage.go
personalities/sctfe/storage/bbolt/dedup.go
personalities/sctfe/storage/gcp/client.go
personalities/sctfe/storage/gcp/doc.go
personalities/sctfe/storage/gcp/issuers.go

Towards #88 
This PR introduces: 
- a standard personality deduplication module with interfaces that allow for global and local implementation. Eventually, the module will be moved out of the SCTFE codebase such that it can be used by other personalities, but let's start by having it here.
- a local deduplication implementation using Bbolt

Deduplicate add-chain requests

---

cmd/posix-oneshot/main.go

The goal here is that the main method should contain only the interesting code for putting the entries in the log. This PR moves code into methods to aid readability:
- initializing the verifier
- initializing the signer
- evaluating the glob

POSIX oneshot: refactor code out of main method

---

cmd/example-posix/main.go
cmd/posix-oneshot/main.go
storage/posix/files.go

The storage layer knows everything required to do this, so this change implements the function internally.

POSIX: storage doesn't take readCP func

---

cmd/example-posix/main.go
cmd/posix-oneshot/main.go
storage/posix/files.go

Both personalities had duplicate code for creating directories and writing out an empty checkpoint. This logic is going to be the same for any POSIX log usage, so it should be part of the log implementation.
For now, this is behind an extra parameter that is passed to New. There may be better ways to set this up, but I tried a few and this was the best. This is a pragmatic step forward and better than what we had, so let's get this in and refactor further from here if needed.
Also cleaned up the `New` method by moving an inline function that was assigned to a field is instead defined as a method.

POSIX: inline log initialization

---

cmd/posix-oneshot/main.go
storage/posix/files.go

This documentation makes it clear when integration is performed in this implementation, and gives a clear motivation in the one-shot tooling for iterating over all of the futures to resolve them.

Documentation for POSIX and one-shot command

---

integration/integration_test.go

Previously this was limping on because calling t.Fatal in a goroutine doesn't kill the whole test. This change propagates the error so that it poisons the error group, causing the test to exit properly. This means that nil checkpoints can't live on inside the slice of collected checkpoints.

Propagate fatal errors in integration tests

---

cmd/examples/posix-oneshot/README.md

A couple of suggestions from independent review; mostly make it clear that ordering of files evaluated by the glob aren't necessarily deterministic, and rename the directory for the leaves to add to make it clearer that it isn't part of the log.

POSIX README nits

---

cmd/conformance/gcp/main.go
cmd/conformance/mysql/main.go
cmd/conformance/posix/main.go

From Request.Body docs: The Server will close the request body. The ServeHTTP Handler does not need to.

HTTP handlers: skip closing the body

---

.github/workflows/benchmark.yml
.github/workflows/integration_test.yml
cmd/conformance/posix/README.md
cmd/conformance/posix/docker/compose.yaml
cmd/conformance/posix/main.go

This simplifies a lot of other code that was spinning up busybox as an http server. This has failed a number of times in CI. The simpler deployment of this approach has a lot going for it. The one downside is that it shows non-canonical usage of the POSIX log. But as there's already an HTTP server running, it seems wasteful to not take advantage in this way.

POSIX conformance: run an HTTP file server

---

cmd/conformance/gcp/main.go

This PR tidies up the GCP conformance code a bit, removes the obsolete read proxy, and adds a few comments.
Towards #8

Tidy GCP conformance code

---

storage/gcp/gcp.go

This PR avoids a potential issue on GCP whereby a checkpoint can be out of date with respect to the log's internal state.
Writes to GCS are rate-limited per object, it's possible that a write to `checkpoint` can be rejected if this limit triggers. If that happens on the final integration run which completely drains the sequenced items in Spanner, then the GCS checkpoint file won't be updated again until new entries are sequenced.
This PR resolves this by simply aborting the integrate run if `checkpoint` is not successfully written (along with any other GCS resources). This means that the whole integration will be retried at the next attempt, which will likely incur the "idempotency" checks on the GCS resources, but it should happen rarely enough that this isn't overly burdensome.
We can …

[GCP] Don't continue if checkpoint not written

---

storage/posix/files.go

This PR fixes an issue where files created using `createExclusive` have `0o600` perms.
This was caused by the use of `os.CreateTemp`, so we now just create a temporary file manually and `Rename` it into the target location. 
#22

[POSIX] Refactor and use createExclusive

---

.github/workflows/integration_test.yml
cmd/conformance/posix/docker/compose.yaml
integration/integration_test.go

#8 #22 
<s>The files created by Docker are always owned by `root`. The integration test cannot read the checkpoints, tiles and entry bundles.</s>

Support `file://` scheme in integration test

---

.github/workflows/terragrunt_test.yml

`tg_dir` is a required GitHub Action input but it is missing at the moment.
https://github.com/gruntwork-io/terragrunt-action?tab=readme-ov-file#inputs

Add required `tg_dir` to Terragrunt format check

---

hammer/client.go
hammer/hammer.go

This PR extends the support within `hammer` by allowing distinct bearer tokens to be used for read and write requests.

[hammer] Allow distinct bearer tokens for read and write clients

---

hammer/hammer.go

This PR "squashes" duplicate errors printed out by the hammer.
When there's an error talking to the target log, the hammer logs the error as a `Warn` entry.
In theory this is great, but in practice errors tend to come in floods which has the unfortunate effect of making it hard to see what's going on because there's a flood of error messages whipping past.
This PR turns a run of identical errors into a single line with a count:
```
W0912 14:44:46.326227 463 hammer.go:341] (129 x) failed to create request: write leaf was not OK. Status code: 500. Body: ...
```

Squash duplicate errors in hammer

---

cmd/conformance/gcp/main.go
deployment/modules/gcp/cloudbuild/main.tf
deployment/modules/gcp/conformance/main.tf
go.mod
hammer/hammer.go

This PR enables the use of HTTP2/Cleartext (h2c) in the GCP conformance server, and adds an flag to optionally _force_ HTTP/2 usage in the hammer.
HTTP/2 supports much better multiplexing of requests over a socket connection compared to HTTP/1.1, which in turn results in better performance and fewer errors when sending a large number of concurrent requests (e.g. when running the hammer against a conformance server).
CloudRun detects and supports h2c if implemented by the server its hosting, otherwise it will [downgrade incoming HTTP/2 requests to HTTP/1](https://cloud.google.com/run/docs/configuring/http2).

Add support for h2c to GCP conformance and HTTP/2 to hammer

---

deployment/live/gcp/cloudbuild/prod/terragrunt.hcl
deployment/live/gcp/conformance/terragrunt.hcl
deployment/modules/gcp/cloudbuild/main.tf
deployment/modules/gcp/cloudbuild/variables.tf
deployment/modules/gcp/conformance/main.tf
deployment/modules/gcp/conformance/outputs.tf
deployment/modules/gcp/conformance/variables.tf
deployment/modules/gcp/gcs/main.tf
deployment/modules/gcp/gcs/outputs.tf
deployment/modules/gcp/gcs/variables.tf

This PR updates the GCP `terra{grunt,form}` configs so that they don't attempt to manage service accounts, as these are being managed externally.

[GCP] Update `terra{grunt,form}` to reflect externally managed service accounts

---

cmd/examples/posix-oneshot/README.md

875977a changed the name of the directory containing leaves but failed to make the change throughout the file. This commit updates the remaining command examples with the new name.

Fix posix-oneshot example directory name

---

cmd/conformance/posix/README.md

The hammer tool gives an error `--log_url must be provided` when executing the example command. Update the flags to match the working command for the mysql example.

Fix hammer command in posix example

---

README.md
cmd/conformance/README.md
cmd/conformance/mysql/main.go
cmd/conformance/posix/main.go

The POSIX and MySQL commands have been updated to output the required
env variables. I'll need some help with the GCP one as we can't assume
localhost and I don't think all the info we need is available. Maybe
this can be output by the terraform script?

Basic codelab for simple HTTP personalities

---

.gitignore
deployment/live/gcp/cloudbuild/prod/.terraform.lock.hcl
deployment/live/gcp/conformance/ci/.terraform.lock.hcl

This ensures that everyone is using the same versions of the terrraform modules when deploying. Added the gitignore files for stuff that shouldn't be committed.

Commit terragrunt lock files

---

cmd/conformance/mysql/main.go
integration/storage_uniformity_test.go
storage/gcp/gcp.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go
storage/posix/files.go

This PR adds the MySQL "read" API onto the other storage implementations.
While we wouldn't generally expect applications to serve the read API directly unless they're using they MySQL storage implementation, we do expect that some subset of applications will want to be able to inspect the state of the tree locally (e.g. in order to expose an API which appears to implement synchronous integration). Such applications are generally going to want to have access to the read-only resources via the same "fast" path as Tessera has rather than the public path which may plausibly involve going via a CDN, waiting for replication, etc. 
#278

Storage impls have a common read API

---

client/client.go
client/client_test.go
client/fetcher.go
integration/integration_test.go
integration/storage_uniformity_test.go
internal/hammer/client.go
internal/hammer/hammer.go
internal/hammer/workers.go
storage/posix/files.go

This PR adapts the `client` package to use tighter scoped functions for fetching different types of log artifact, as opposed to the more generic "fetchURL" approach it previously took.
These tighter function signatures match the ones in #281, allowing personality authors to directly use storage instances when e.g. building off-line proof bundles etc.

Add tighter-scoped function types in /client

---

cmd/conformance/gcp/main.go
cmd/conformance/mysql/main.go
cmd/conformance/posix/main.go
deployment/live/gcp/cloudbuild/prod/terragrunt.hcl
deployment/live/gcp/conformance/ci/terragrunt.hcl
deployment/live/gcp/conformance/terragrunt.hcl
deployment/modules/gcp/cloudbuild/variables.tf
deployment/modules/gcp/conformance/main.tf
deployment/modules/gcp/conformance/variables.tf
log.go

This PR allows Tessera to be configured with multiple checkpoint signers.
This is useful when rotating the key of a log whilst avoiding having to coordinate a global "flag day" for everyone to switch over, or for situations where different audiences of a log require different signature schemes.

Multiball signatures

---

await.go

The blank line meant that in pkg.go.dev, the important first paragraph was not rendered.

Fix comment for IntegrationAwaiter

---

ct_only.go
internal/options/options.go
log.go
storage/gcp/gcp.go
storage/internal/options.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go
storage/posix/files.go

I'm looking over https://pkg.go.dev/github.com/transparency-dev/trillian-tessera and making it clearer to newcomers.
This moves fields and types into internal, which is more refined approach to the file-based solution taken thus far to #280.

Move stuff to internal and improve comments

---

client/fetcher.go

This PR fixes an error in the formatting of the `Authorization` header for requests sent by the client HTTP fetcher.

Fix auth formatting in client requests

---

internal/hammer/client.go

This PR fixes an error in the `Authorization` header used by the hammer client.

Fix hammer auth header too

---

deployment/modules/gcp/cloudbuild/main.tf

This PR improves the resilience of the GCP CI pipeline.
When something goes wrong with a CI run, GCB bails and stops progressing through the configured steps. This means that we don't get to the "clean up and tear down" step right at the end.
Unfortunately there seems to be no way to instruct GCB that a particular step must run regardless of whatever else has happened, the nearest thing is the ability to tag individual steps as being "fail ok", but of course in reality they're not and so this complicates future steps as they need to figure out for themselves whether previous steps actually failed.
Instead, this PR simply attempts to tear down any resources in the CI env as the very first build step.
#7

Pre-clean conformance env

---

internal/hammer/hammer.go
internal/hammer/hammer_test.go

Previously this would only create consecutive duplicates. Now it can create duplicates covering the whole rangeof the log.
This fixes #293.
Also made the threading semantics clearer, as this was performing reads and writes from multiple threads on an unprotected uint64.

Generate duplicates over whole log range

---

storage/gcp/gcp.go

This PR fixes a bug in the GCP `ReadEntryBundle` implementation, which would have broken attempts to read from Static CT API logs.

Fix GCP ReadEntryBundle to use configured path

---

cmd/conformance/aws/Dockerfile
cmd/conformance/aws/README.md
cmd/conformance/aws/main.go

Towards #24 and #312
This PR copies the gcp conformance test for aws. A followup PR will migrate it to the new aws Tessera storage.

Copyconformance

---

cmd/conformance/aws/Dockerfile
cmd/conformance/aws/main.go

Towards #24 and #312 
Verified that `docker build -f ./cmd/conformance/aws/Dockerfile .` works.
This PR uses password based authentication for now, which is good enough to start with. I've tested IAM based authentication, which works. Let's get all the terraform in with passwords, and then we can eventually move to IAM.
While we're there, get rid for verifiers in `signerFromFlags` since we don't use them anymore.

Conformance binary for AWS

---

.github/workflows/go_test.yml
go.mod
go.sum
storage/aws/aws_test.go

Towards #312 and #24.
This PR builds upon the GCP tests, and migrates them to MySQL and S3.
This file contains some MySQL and some non-MySQL tests. MySQL tests should only run if a MySQL database is available, inspired by the `storage/mysq/mysql_test.go` setup. I tried a bunch of setups with "TestMain" and "t.Clean", and settled on this setup with two helper methods, and disabling parallel tests.
This PR has two commits: one that moves tests, and one that migrates them to AWS to ease reviewing (separating them into two PRs is challenging because of package names and private functions).

AWS storage implementation tests

---

storage/aws/aws.go
storage/gcp/gcp.go

These messages attempt to better reflect hat:
- the bundle in S3/GCS are do not necessarily exist yet
- write are attempted, but preconditions might prevent them from happening
Context: I wanted to double check what would happen in real life if bad data was already written to a tile / entry. I created a dummy entry bundle life idx X beyond the current checkpoint, and launched the hammer. I was a bit confused to see "Bundle idx X is full" in the log messages, since I knew that the precondition should have avoided Tessera from writing a bundle at entry X.
Please, a better wording suggestion is more than welcome!

attempt to improve log messages

---

log.go

The previous docs were inadequate as the obvious inference was that batching was disabled if this method wasn't called. The new docs explain that this only configures the sequencer.

Updated docs for WithBatching

---

storage/aws/aws.go
storage/gcp/gcp.go
storage/internal/integrate.go
storage/internal/integrate_test.go
storage/mysql/mysql.go
storage/posix/files.go

This code previously had a number of mutexes but no obvious concurrency. Access to some of the mutex-protected fields on populatedTile was questionable; the Equals method had no locks on either object, and the leaves were directly read by another object. Instead of trying to address these by adding more locks, the TreeBuilder object has been moved to be internal, and Integrate is now a function. This makes the state and concurrency much easier to reason about.
Added a benchmark for Integrate.

Clean up integration code

---

entry.go
storage/internal/queue_test.go

This is vestigial after the changes to make deduplication be a personality concern. We _may_ want to add opts back in the future, but we can do that as we need it.

Removed EntryOpts

---

deployment/live/aws/conformance/ci/README.md
deployment/live/aws/conformance/ci/terragrunt.hcl
deployment/live/aws/conformance/terragrunt.hcl
deployment/modules/aws/storage/main.tf
deployment/modules/aws/storage/variables.tf

Towards #312
This PR introduces Terraform for AWS storage backend. More work is underway for the other components, see #312.
Putting aside the fact that this runs on AWS (RDS + S3) rather than GCP (Spanner + GCS) , other differences are:
- AWS doesn't really have a concept of human readable project IDs, project IDs are numbers, so I've introduced a human readable "prefix" used across resources instead
- Terragrunt on GCP uses GCS precondition to lock state. That's not an option (yet?) on AWS, it uses a DynamoDB database

AWS backend terraform + Readme

---

deployment/modules/gcp/cloudbuild/main.tf

The existing Cloud Build log is full of the color formatting sequences in the output. Removing them improves the log readability.
```
2024-11-20 16:36:08.304 GMT
Step #0 - "preclean_env": [0;90m16:36:08.303 [0m[0;37mSTDOUT [0m[0;36mterraform: [0m[0m[1mInitializing the backend...[0m[0m
2024-11-20 16:36:08.386 GMT
Step #0 - "preclean_env": [0;90m16:36:08.385 [0m[0;37mSTDOUT [0m[0;36mterraform: [0m[0m[32m[0m
2024-11-20 16:36:08.386 GMT
Step #0 - "preclean_env": [0;90m16:36:08.385 [0m[0;37mSTDOUT [0m[0;36mterraform: [0mSuccessfully configured the backend "gcs"! Terraform will automatically
2024-11-20 16:36:08.386 GMT
Step #0 - "preclean_env": [0;90m16:36:08.386 [0m[0;37mSTDOUT [0m[0;36mterraform: [0muse this backend unless the backend configuration …
```

Remove color from terragrunt/terraform log in GCP Cloud Build

---

cmd/conformance/aws/main.go
cmd/conformance/gcp/main.go
cmd/conformance/mysql/main.go
cmd/conformance/posix/main.go
dedupe.go
dedupe_test.go
go.mod
go.sum
storage/internal/queue.go
storage/internal/queue_test.go

This allows the deduplication behaviour to be more precisely controlled by the personality. Previously deduping was always performed within a single batch flushed from the queue, and this could not be disabled. Now, deduping can be disabled, or made to apply across batches if a large enough cache size is set.
The conformance binaries have been updated to use this new mixin, as this is the closest to a no-op change I can make. We may want to look at making the cache size configurable and see how this affects performance.
This fixes #331.

Pull dedupe out of queue and into personality mixin

---

integration/integration_test.go

This PR makes the integration test more resilient to the log behaviour introduced in #333.
Currently the integration test will likely work the first time it's run, but if it's run a second time against the same log, it will likely fail when fewer entries than it expected were added to the log due to deduping.
The changes in this PR remove that assumption about size of tree growth, but the test continues to verify that all entries are nonetheless present.

Fix integration test expectations

---

cmd/conformance/gcp/README.md
deployment/live/gcp/conformance/README.md
deployment/live/gcp/conformance/ci/README.md
deployment/live/gcp/conformance/ci/terragrunt.hcl
deployment/live/gcp/conformance/terragrunt.hcl
deployment/modules/gcp/cloudbuild/main.tf
deployment/modules/gcp/conformance/main.tf
deployment/modules/gcp/conformance/variables.tf

This PR makes the `terra{grunt,form}` config for deploying the GCP conformance environment more friendly for humans to use when exploring Tessera.
The main changes are:
- Service accounts are now optional
- Docker image to use for CloudRun can be specified
- Docs updated to guide humans along the path to deploy

[GCP] Make the GCP conformance deployment config more friendly

---

cmd/conformance/README.md
deployment/live/aws/codelab/README.md
deployment/live/aws/codelab/terragrunt.hcl
deployment/modules/aws/codelab/main.tf
deployment/modules/aws/codelab/outputs.tf
deployment/modules/aws/codelab/variables.tf
deployment/modules/aws/storage/main.tf
deployment/modules/aws/storage/outputs.tf

Towards #312 and #24
This PR adds a terraform module, terragrunt config and documentation to launch a Trillian Tessera test stack from an AWS EC2 VM, and to launch a conformance binary on that VM.
It brings minor modifications to the base /storage module, which will be also relied on for the CI environment.

Instructions to launch a test instance from a VM

---

cmd/conformance/mysql/main.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go
storage/mysql/schema.sql

This PR disconnects the act of integrating new entries into a tree, from the act of publishing a new checkpoint which publicly commits to that new tree state for the MySQL storage implementation.
See #323 for more details on the rationale.
Helps with #309 and #198.

[MySQL] Separate integration from publishing checkpoints

---

docs/design/README.md
storage/mysql/README.md

The links to the storage design are broken after moving them around in https://github.com/transparency-dev/trillian-tessera/pull/350.

Fix storage design doc broken links

---

deployment/modules/gcp/conformance/main.tf
deployment/modules/gcp/gcs/main.tf

Added missing API, and pinned the version of terraform to a known working version. 1.10.0 was recently released which breaks this in a hard to debug way.

[GCP Terraform] improved stability for deployment

---

docs/performance.md
storage/mysql/PERFORMANCE.md
storage/posix/PERFORMANCE.md

This PR replaces `docs/performance.md` with more of a high-level summary, and moves the more detailed information out to `PERFORMANCE.md` docs in each of the storage implementation directories.
The goal is to have the `docs/performance.md` give more of an overview of aspects which affect performance, and broad strokes on what to expect from each of the storage implementations.

Update performance docs

---

deployment/modules/gcp/cloudbuild/main.tf

Bump `alpine/terragrunt` from 1.9.5 to 1.9.8 in GCP Cloud Build

---

cmd/conformance/README.md

I got unexpected result when running the codelab instructions.
```sh
[ec2-user@ip-172-31-24-203 ~]$ # Add 3 entries in parallel, and wait for all requests to complete
curl -d 'one!' -H "Content-Type: application/data" -X POST ${WRITE_URL}add &
curl -d 'two!' -H "Content-Type: application/data" -X POST ${WRITE_URL}add &
curl -d 'three!' -H "Content-Type: application/data" -X POST ${WRITE_URL}add &
wait
curl -s ${READ_URL}checkpoint
curl -s ${READ_URL}tile/entries/000.p/3 | xxd
[1] 32012
[2] 32013
[3] 32014
012[1]   Done                    curl -d 'one!' -H "Content-Type: application/data" -X POST ${WRITE_URL}add
[2]-  Done                    curl -d 'two!' -H "Content-Type: application/data" -X POST ${WRITE_URL}add
[3]+  Done                    curl -d 'three!' -H "Content-Type: …
```

Update conformance codelab instructions

---

.github/workflows/aws_integration_test.yml
deployment/live/aws/conformance/ci/terragrunt.hcl
deployment/live/aws/conformance/terragrunt.hcl
deployment/modules/aws/conformance/main.tf
deployment/modules/aws/conformance/outputs.tf
deployment/modules/aws/conformance/variables.tf

Towards #312.
This PR introduces a CI pipeline for AWS Tessera running on GitHub actions.
On every push to `main`, a GitHub action:
1. authenticates with the trillian-tessera AWS account using secret keys stored on GitHub
1. builds the `conformance` and `hammer` docker images
1. pushes them to a container registry on AWS
1. brings down old ci environments if need be
1. generates Tessera keys
1. brings up a new ci environment with:
- an Aurora RDS DB
- an S3 bucket
- an ECS cluster
- an ECS Fargate service running multiple instances of the conformance binary
- it defines (but does not launch) an ECS Fargate hammer task
1. launches the hammer task against the conformance service, and waits for it to return
1. brings down the full task
The whole process takes around 30 minutes to complete, …

AWS CI pipeline

---

cmd/conformance/aws/main.go
storage/aws/aws.go
storage/aws/aws_test.go
storage/gcp/gcp.go
storage/internal/integrate.go

This PR disconnects the act of integrating new entries into a tree, from the act of publishing a new checkpoint which publicly commits to that new tree state for the MySQL storage implementation.
See #323 for more details on the rationale and the GCP and POSIX implementations, and #344 for the MySQL implementation.
Helps with #309 and #198.
Tested on AWS:
```
│I1204 15:20:09.138000   38710 hammer.go:242] Updated checkpoint from 236544 to 252928 │
│I1204 15:20:12.619872   38710 hammer.go:242] Updated checkpoint from 252928 to 270336 │
│I1204 15:20:16.585067   38710 hammer.go:242] Updated checkpoint from 270336 to 286720 │
│I1204 15:20:21.142250   38710 hammer.go:242] Updated checkpoint from 286720 to 302080 │
│I1204 15:20:25.144099   38710 hammer.go:242] Updated checkpoint from 302080 to …
```

[AWS] Separate integration from publishing checkpoints

---

log.go
storage/internal/options.go

This PR moves the default values next to the `WithOptions` which can alter them.
This makes it easier to discover the defaults and corresponding documentation on the options.

Move default consts

---

cmd/conformance/mysql/main.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go

Major changes:
- MySQL storage read methods return os.ErrNotExist when values aren't found
- ReadTile returns an error if the user requests more data than we have available
- Added tests for writing and reading data from tiles
- Made tests hermetic (though slower) by resetting the DB for each test case
This got a bit bigger than intended.
This fixes #364.

[MySQL Conformance] fix tree size bug

---

deployment/live/gcp/conformance/README.md

I bundled a few things from my friction log into one change. let me know if that works.

polish gcp getting started doc

---

storage/mysql/mysql_test.go

Awaiting in the loop was causing this to take ages as it was doing one leaf at a time. They now happen in parallel, and we make sure they're all done before we allow the read parts of the test to start.

[MySQL] make the tests go faster

---

cmd/conformance/mysql/main.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go

IsNotExist returns a boolean indicating whether its argument is known to report that a file or directory does not exist. It is satisfied by [ErrNotExist](https://golang.google.cn/pkg/os/#ErrNotExist) as well as some syscall errors.
This function predates [errors.Is](https://golang.google.cn/pkg/errors/#Is). It only supports errors returned by the os package. New code should use errors.Is(err, fs.ErrNotExist).
https://golang.google.cn/pkg/os/#IsNotExist

Replace `os.IsNotExist(err)` with `errors.Is(err, fs.ErrNotExist)`

---

api/state_test.go
storage/internal/integrate_test.go

Parsing entry bundles needs to be fast, so locked that in with a benchmark. While looking at other benchmarks, I noticed integrate wasn't using b.N, so wired that into the test instead of constant we already had to control the number of loops.

Added and updated benchmarks

---

api/layout/example_test.go
api/layout/paths.go
api/layout/paths_test.go
api/layout/tile.go
api/state.go
client/client.go
client/client_test.go
client/fetcher.go
cmd/conformance/mysql/main.go
ct_only.go
ct_only_test.go
integration/storage_uniformity_test.go
internal/hammer/client.go
internal/options/options.go
storage/aws/aws.go
storage/aws/aws_test.go
storage/gcp/gcp.go
storage/gcp/gcp_test.go
storage/internal/integrate.go
storage/internal/integrate_test.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go
storage/posix/files.go

This PR replaces the use of `logSize` on the exported storage APIs with the explicit desired partial tile/entry bundle size.
There are different classes of users of these APIs which will naturally favour one these approaches (e.g. clients must have a checkpoint in their possession and so always know the log's size), but whereas it's trivial to go from `logSize` to the implied partial tile/entry bundle width, the inverse is not.
This PR redresses the imbalance by flipping over to using partial tile widths where appropriate, and exporting the function for calculating partial tile widths from tile coordinate and log size.

Storage API uses partial width rather than logSize

---

await.go
cmd/examples/posix-oneshot/main.go
storage/aws/aws.go
storage/gcp/gcp.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go
storage/posix/files.go

This PR defines minimum checkpoint publication intervals for the storage implementations, and they will now return an error if an invalid interval is set via the `WithCheckpointInterval` option.

Storage implementations enforce minimum checkpoint intervals

---

client/client.go
storage/gcp/gcp_test.go

This PR fixes a bug introduced in #393 where an incorrect value for entry bundle width is calculated, which will frequently result in an entry bundle incorrectly not being found.

Just use layout.PartialTileSize

---

storage/gcp/gcp.go
storage/gcp/gcp_test.go

This PR changes the GCP storage implementation such that it explicitly sets `CacheControl:` headers.
Towards #399

[GCP] Add CacheControl headers

---

cmd/conformance/mysql/main.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go
storage/mysql/schema.sql

MySQL API now checks that the number of entries returned in a bundle is not smaller than the number requested. It does this by parsing the entry bundle. This could be optimized by storing the bundle size in the table.
Now this is fixed, the conformance personality is updated to set cache headers on the entry bundles to allow aggressive caching. Also fixed the checkpoint implementation to never cache, and handle not found properly.
This fixes #364.

[MySQL] complete entry bundle implementation

---

deployment/live/aws/codelab/README.md

Explain how to run terragrunt destroy

---

.github/workflows/benchmark-go-main.yml
.github/workflows/benchmark-go-pr.yml
.github/workflows/benchmark-go.yml

This should always leave a comment with a summary of benchmark results. Furthermore, if the alert threshold is triggered then it will leave another comment making it clear that this has happened.
I fully expect that we'll want to disable at least one of these, and possibly tune the alert threshold. But by starting with too much, it will be fast to see and back this off to a useful level.

[Benchmarks] Comment on PRs with benchmark scores

---

cmd/conformance/posix/main.go

Add cache headers to POSIX version too.

Add cache headers to POSIX version too

---

cmd/conformance/mysql/main.go

This PR removes the `public` component of the `Cache-Control` header served by the MySQL conformance FE.
AFAICT `public` is the default, and only really needs to be added if the response is to a request which required the `Authorization` header, and that response should be made cacheable by public caches.
From https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#public :
> If a request doesn't have an Authorization header, or you are already using s-maxage or must-revalidate in the response, then you don't need to use public.

Remove public from mysql conformance cache-control

---

ctonly/ct.go

This PR fixes an error in the serialisation of Static CT API leaf data.
The `ctonly` package could do with some golden tests, I've added #420 to track that.

Fix CT serialisation

---

internal/hammer/hammer.go

This should avoid the weird number that can be reported when changing the limits at runtime. This also cleans up the readability of the main supply loop, avoiding the need to have a label to break to.

[Hammer] Throttle has mutex guarding changes

---

ctonly/ct.go

This PR rolls-back the changes in #421 which were wrong, and adds some comments to the struct and serialisation code to make it clearer what's going on.

Rollback #421 and add some comments

---

cmd/conformance/aws/main.go
storage/aws/README.md
storage/aws/aws.go

This PR enables the `aws` storage implementation to be used with `MySQL` and `S3` compatible storage services outside of the `AWS` environment.
Such usage is unsupported; folks doing this must verify that things are working correctly themselves. That said, this change has been (very minimally and quickly) tested locally with MariaDB and a local MinIO server running in docker.

Open AWS storage to being used with non-AWS MySQL and S3 services

---

storage/aws/aws.go
storage/gcp/gcp.go
storage/internal/integrate.go
storage/internal/integrate_test.go
storage/mysql/mysql.go
storage/posix/files.go

This PR updates the integration helper to only require knowledge of leaf hashes, it should not need to know anything else about the leaves.
This minor change helps with modularity, and opens the door to using the helper in other log lifecycle modes (e.g. migration #436 ).

Integrate operates in terms of hashes

---

storage/posix/files.go

This PR fixes a couple of small issues in the POSIX storage, and tidies it up a bit.

[POSIX] Fixes & tweaks

---

storage/aws/README.md
storage/aws/aws.go
storage/gcp/README.md
storage/gcp/gcp.go
storage/gcp/gcp_test.go
storage/mysql/mysql.go
storage/posix/README.md

This PR pulls the act of updating the merkle tree resources out into separate funcs.
This helps with readability by reducing the size/tightening the scope of some of the funcs in storage implementations (MySQL in particular was getting quite large), but also aids in supporting other lifecycle modes (e.g. for #414). 
No functional changes.

Extract tighter-scoped integrate funcs in storage impls

---

.github/workflows/go_test.yml
cmd/conformance/mysql/docker/Dockerfile

This PR bumps GHA workflows in preparation for bumping the `go.mod` file to `1.23`.

Bump workflows in prep for Go 1.23

---

api/layout/paths.go
api/layout/paths_test.go
cmd/experimental/migrate/internal/migrate.go
cmd/experimental/migrate/posix/main.go
go.mod
go.sum
storage/posix/files.go

This PR adds experimental migration support for migrating into POSIX logs.
Towards #436

Experimental migration support for POSIX

---

internal/hammer/hammer.go
internal/hammer/hammer_test.go
internal/hammer/loadtest/client.go
internal/hammer/loadtest/workerpool.go
internal/hammer/loadtest/workers.go

This isn't the full job, as the core of the hammer needs extracting from
hammer.go. This is a good start and sets the right direction for making
this a general purpose library for use in true tlog-tiles and the static
CT variation.

[Hammer] Refactor to allow code reuse with CT

---

deployment/modules/gcp/cloudbuild/main.tf
deployment/modules/gcp/conformance/main.tf
deployment/modules/gcp/conformance/outputs.tf

This PR should get the hammer working again in GCP CI.

Output conformance bucket and use in GCB

---

deployment/modules/gcp/cloudbuild/main.tf

This PR renames the cloud build trigger to be more descriptive of what it's doing.

Rename GCB trigger to better match the intended purpose

---

internal/hammer/hammer.go
internal/hammer/hammer_test.go
internal/hammer/loadtest/analysis.go
internal/hammer/loadtest/analysis_test.go
internal/hammer/loadtest/hammer.go
internal/hammer/loadtest/throttle.go
internal/hammer/loadtest/tui.go

This is a rough approximation of what a library version of the hammer
could look like. The remaining code in the outer `main` package is now
the tlog-tiles specific stuff. The code in the `loadtest` package should
be configurable to use with Static CT.
Towards https://github.com/transparency-dev/static-ct/issues/59.

[Hammer] Moved more common functionality into loadtest package

---

storage/mysql/DESIGN.md
storage/mysql/mysql.go
storage/mysql/schema.sql

The version is written at schema creation, and checked on startup. If they are different, it fails. Towards #450.

[MySQL] Check that the DB schema is compatible

---

.github/workflows/benchmark-go-main.yml
.github/workflows/benchmark-go-pr.yml

These two actions had the same name in the GH actions tab and that makes it hard to glance at where the problem is, and communicate about it. Unique naming is good.

[Cleanup] Rename benchmark actions

---

lifecycle.go

This PR fixes a bug introduced in #433 which causes a `panic` when attempting to use decorators on `NewAppender`.

Fix broken decorators

---

cmd/conformance/gcp/main.go
storage/gcp/gcp.go
storage/gcp/gcp_test.go

This PR updates the experimental GCP dedup implementation with a (still experimental) version which populates its database by tailing the log, as opposed to the with many potentially-competing transactions it does currently.
This approximately doubles the throughput when running on the same infrastructure.
Towards #470

Replace GCP dedup with follower-style implementation

---

storage/posix/files.go
testdata/build_log.sh

This PR tightens the semantics of the file operations performed by the POSIX storage implementation.
It splits "writing files" across 3 narrower funcs which are then called by the storage driver depending on exactly which behaviour is intended.

Tighten up POSIX file operations

---

cmd/conformance/aws/main.go
cmd/conformance/gcp/main.go
cmd/conformance/mysql/main.go
cmd/conformance/posix/main.go
cmd/examples/posix-oneshot/main.go
lifecycle.go
storage/mysql/mysql_test.go

The inflexibility of this was noticed while looking at options to fix https://github.com/transparency-dev/trillian-tessera/issues/341. This PR includes a comment indicating that in future we want to add a Shutdown method, but more interesting are the other changes that:
a) move the dedupe decorators behind an options, and
b) making Appender more than just a function to allow new methods (such as Shutdown) to be added in the future.

[API] Refactoring to make appender API future-proof

---

ct_only.go

Track changes in lifecycle API introduced in #482

Update CT support to match lifecycle change

---

storage/posix/files.go

If two tasks attempted to initialise an empty checkpoint, and one task
stalled while the other began accepting traffic, then the tree state and
checkpoint would be invalidated by the stalled task. This guarantees
initialisation only once per log.
Fixes #476

Lock initialise to prevent concurrent initialisation 

---

witness.go
witness_test.go

This allows the required witnesses to be defined and the theshold
policies that apply within each group. Arbitrarily nested structures can
be built, each with different numbers of signatures.
Each WitnessGroup provides the URLs at which the witness can be reached
to perform witnessing, and a function that determines if the group is
satisfied.
This format is consistent with the only other known witness policy
configuration format out there:
https://git.glasklar.is/sigsum/core/sigsum-go/-/blob/main/doc/policy.md
Towards #309.

Defined witness policy configuration

---

cmd/conformance/aws/main.go
cmd/conformance/gcp/main.go
cmd/conformance/mysql/main.go
cmd/conformance/posix/main.go
lifecycle.go
storage/aws/aws.go
storage/gcp/gcp.go
storage/gcp/gcp_test.go
storage/mysql/mysql.go
storage/posix/files.go

This PR introduces a `WithAntispam` option which handles both the in-memory and an (optional) persistent antispam implementation.
Towards #469

Antispam WithOption

---

cmd/experimental/migrate/gcp/main.go
cmd/experimental/migrate/internal/migrate.go
cmd/experimental/migrate/posix/main.go
lifecycle.go
storage/gcp/gcp.go
storage/posix/files.go

This PR adds `MigrationTarget` support to the lifecycle/driver API, and updates the POSIX and GCP implementations to match.
Towards #414 #471 #472

Add Migration lifecycle support

---

internal/witness/witness.go
internal/witness/witness_test.go
witness.go
witness_test.go

This now verifies the body of 200 responses. It checks that the note can
be verified using the signature, and then returns only the signature
that the log has a verifier for.
This means that witnesses that return a valid signature and then a load
of other signatures will not be able to pollute the checkpoint with
these other signatures. On the other hand, it means we will need to
consider how to support witness key rotation in Tessera in the future.
There are a few ways to solve this, but I don't believe this approach
blocks any of them.

[Witnessing] Check responses for valid signatures

---

storage/gcp/gcp.go
storage/gcp/gcp_test.go

This PR does some small tidying up in `gcp.go`, no functional changes are intended.
* Group structs and their methods together
* Rename `spannerSequencer` to `spannerCoordinator` to better reflect what it does
* Reduce size of `Appender` func by extracting inline anonymous worker funcs.
* Make method receivers on `Appender` be named consistently

Tidy gcp.go

---

cmd/experimental/migrate/gcp/main.go
cmd/experimental/migrate/posix/main.go
ct_only.go
lifecycle.go
storage/gcp/gcp.go
storage/posix/files.go

This PR adds `MigrationOptions` to be used with the migration target lifecycle.

Migration lifecycle options

---

cmd/experimental/migrate/gcp/main.go
migrate_lifecycle.go
storage/gcp/gcp.go

This PR adds an antispam option to the Migration lifecycle, and shows its use in the GCP migrate tool.
Towards #469

Add antispam support to migration lifecycle

---

internal/hammer/loadtest/hammer.go

If the checkpoint size isn't updating, this logging will at least allow visibility that the main loop is still running.

[Hammer] support more verbose checkpoint logging

---

cmd/experimental/migrate/mysql/main.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go

This PR adds support to the MySQL storage implement for the Migration lifecycle mode, and adds an experimental migrate tool.
Towards #474

[MySQL] Add support for Migration lifecycle

---

internal/witness/witness.go
internal/witness/witness_test.go

Previously the state was being lost. Even though this was unintentional, it worked, but involved constantly querying the witness as if it was at size 0.
This change makes the size sticky for the life of the process by correctly using pointers instead of copying structs. It also updates the size on success, which was missing earlier.

Fix witnessed size state

---

await.go
internal/parse/parse.go
internal/parse/parse_test.go
internal/witness/witness.go
internal/witness/witness_test.go

This switches away from the previous idea which was to pass in a proof
fetcher. Now a tile fetcher is passed in, and the proofs are constructed
in the witness code.
Now that real proofs are being generated, we need to use a real log in
the witness tests. The POSIX log in testdata is used for this purpose.
The unsafe method for parsing checkpoints has also been extended to
return hashes, which was needed to support this work.
Towards #309.

[Witness] construct proofs in witness

---

internal/witness/witness_test.go
storage/aws/aws.go
storage/gcp/gcp.go
storage/mysql/mysql.go
storage/posix/files.go

All drivers now take set up witnessing as configured in the AppendOptions. If no options are provided then this is still set up, but does nothing. Towards #309.  This required changing the witness tests package to avoid a package cycle; the posix implementation now uses the witness, but the witness tests use posix.
This is based on #514, and that needs to be merged first.

[Witnessing] Use witnessing in all drivers

---

cmd/conformance/gcp/main.go
cmd/experimental/migrate/gcp/main.go
deployment/live/gcp/conformance/ci/terragrunt.hcl
deployment/modules/gcp/conformance/main.tf
deployment/modules/gcp/conformance/variables.tf
deployment/modules/gcp/gcs/main.tf
deployment/modules/gcp/gcs/variables.tf

This PR adds support for:
- the GCP terraform to optionally create infrastructure used by the GCP antispam implementation.
- the conformance terraform to optionally create and use the GCP antispam support.
As a side-effect, the naming scheme for the Spanner databases has changed very slightly.
Towards #470

[GCP] Add persistent anti-spam support to terraform

---

append_lifecycle.go
cmd/experimental/migrate/gcp/main.go
cmd/experimental/migrate/mysql/main.go
cmd/experimental/migrate/posix/main.go
ct_only.go
ct_only_test.go
lifecycle.go
migrate_lifecycle.go
storage/gcp/gcp.go

This PR adds necessary hooks and implementations for TesseraCT to implement a CT-specific tool for migrating [static-ct](https://c2sp.org/static-ct) compliant logs.
Towards #495

Add CT support for migration

---

append_lifecycle.go
cmd/conformance/aws/main.go
cmd/conformance/gcp/main.go
cmd/conformance/mysql/main.go
cmd/conformance/posix/main.go
cmd/examples/posix-oneshot/main.go
internal/witness/witness_test.go
lifecycle.go
storage/aws/aws.go
storage/gcp/gcp.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go
storage/posix/files.go

This is a revised attempt at Shutdown that is intended to replace #524.
This implementation doesn't have the granular integration with the
channels in each implementation. Instead, it is implemented at the top
level of the appender lifecycle, and each driver doesn't need to have
very similar duplicated code for handling this.
The previous attempt was also trying to make it so that Shutdown would
close out channels and kill goroutines etc. This approach makes it clear
that the way to do this is to cancel the original context passed into
the appender.
Fixes #341.

[Shutdown] Implement Shutdown in a single location

---

cmd/experimental/migrate/gcp/main.go
cmd/experimental/migrate/mysql/main.go
cmd/experimental/migrate/posix/main.go
migrate.go
storage/mysql/mysql.go

This PR exposes the underlying feature used by the experimental migrate commands for use by applications directly.
This is enables "higher level" migration tools to be built - e.g. a Static CT migration tool which will migrate other specified resources in addition to the ones which form the Merkle tree.
Towards #523

Expose migrate functionality to applications built with Tessera

---

README.md
README_test.go

This PR improves the main `README.md` file.
It:
- Tidies up a few nits.
- Adds some visual cues for tips and notes.
- Makes example code in the README be testable, by adding a new `README_test.go` file which is the canonical source for code examples in the readme (which can be updated using the tool mentioned in the comment at the top of the `README_test.go` file.

Improve main README file

---

storage/gcp/gcp.go

This PR makes `MigrationStorage.buildTree` always return values which reflect the current state of the tree, even if no work was done. This removes the potential for confusion, as previously zero values would be returned in this case.

Return current state of tree even if no work done

---

deployment/live/aws/codelab/README.md

Warning when running it with latest release of terraform:
```
14:38:16.962 WARN   The `--terragrunt-working-dir` flag is deprecated
and will be removed in a future version of Terragrunt. Use
`--working-dir=deployment/live/aws/codelab/` instead.
```

[Docs] Fix deprecated flag

---

cmd/experimental/migrate/aws/main.go
storage/aws/aws.go

This is based on the GCP migration target implementation.
The conformance cmd was updated to move the listen flag in order to keep
all common AWS configuration flags together, and the flags for the
application logic built on top (e.g. web serving) in another block.
Tested in AWS and it migrated a POSIX log with 189k entries in 7s.
Fixes #473.

AWS migration target support

---

append_lifecycle.go
cmd/experimental/migrate/aws/main.go
cmd/experimental/migrate/gcp/main.go
cmd/experimental/migrate/mysql/main.go
lifecycle.go
migrate_lifecycle.go
storage/gcp/antispam/gcp.go

This PR defines a `Follower` interface which enables Tessera to know when it's safe to exit, e.g. during migration, we need to potentially wait for the antispam index to be fully populated.
Towards #436

Add richer Follower interface enabling clean shutdown & stats

---

storage/aws/aws.go
storage/gcp/gcp.go
storage/mysql/mysql.go
storage/posix/files.go

All storage backends will log when a new checkpoint is published.
Tiny change to standardize logging message for integration as well.

Standardize logging when publishing a checkpoint

---

storage/gcp/antispam/gcp.go
storage/gcp/antispam/gcp_test.go

This PR adds a simple test for the GCP antispam implementation.
Unfortunately, due to `spannertest` not supporting `BatchWrite`, I've had to add a somewhat unpleasant hook to make this possible, but at least by doing so we can exercise a fair amount of the implementation.

Add GCP antispam test

---

.github/workflows/go_test.yml
cmd/conformance/aws/Dockerfile
cmd/conformance/gcp/Dockerfile
cmd/conformance/mysql/docker/Dockerfile
cmd/conformance/posix/docker/Dockerfile
go.mod
internal/hammer/Dockerfile

This PR bumps the `go.mod` file to `1.24`, along with actions/dockerfiles etc.
TesseraCT is already at `1.24`, and this gives us nice things like `t.Context()` for tests etc.

Bump to Go 1.24

---

.github/workflows/benchmark-go-pr.yml

This PR stops the benchmark action from recording a check fail on PRs if the performance delta is over the threshold.
While it's useful to track benchmark history, the "fails" we've seen are almost all false positives due to the environment in which the benchmark is running. So, for now at least, this PR will remove the likely undeserved red X from PR checks, which should remove a bit of cognitive load from reviewers ("ah, _that_ failure is ok, but not _this_ one", etc.)

Don't fail PR check for benchmarking

---

storage/gcp/antispam/gcp_test.go
testonly/testlog.go

This PR enables easy creation of an ephemeral POSIX-based log for use in tests, and then uses it in the GCP antispam test.

Add support for ephemeral testing logs, and use it in GCP antispam test.

---

storage/aws/antispam/aws.go
storage/aws/antispam/aws_test.go

This adds experimental support for antispam (dedupe) for AWS-hosted
logs. The hashes and indices of seen entries are stored in a MySQL
database.
This is based heavily on the GCP Spanner version, and still maintains
its core way of operation (i.e. filling in the duplicates by using the
Follower pattern).
Towards #526.

[AWS] Antispam

---

storage/aws/aws.go
storage/aws/aws_test.go

This fixes #399 for AWS, and is the last storage implementation so fixes the whole issue.

[AWS] Set cache headers for artifacts in s3

---

go.mod

Exclude directives break running commands in the repository in the
normal go run way:
```shell
go run github.com/transparency-dev/trillian-tessera/cmd/examples/posix-oneshot@main --storage_dir=/tmp/mylog --initialise
The go.mod file for the module providing named packages contains one or
more exclude directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```
I've run `go mod tidy` after this and it seems OK. We'll need to keep an
eye for dependabot making a mess.

Fixed go.mod file to remove exclude

---

storage/aws/antispam/aws_test.go
storage/gcp/antispam/gcp_test.go

These tests were waiting for 10s before finishing. Publishing the checkpoint faster allows this to exit in 1.5s each, instead of 10s each.

[Antispam] Faster tests

---

append_lifecycle.go
internal/witness/witness.go
storage/aws/aws.go
storage/aws/aws_test.go
storage/gcp/gcp.go
storage/gcp/gcp_test.go
storage/mysql/mysql.go
storage/posix/files.go

This PR consolidates responsibility for dealing with getting checkpoints witnessed in the lifecycle layer, removing the need for storage implementations to be aware of it.
This is a continuation of the approach taken for creating checkpoints and signing them.
Down the line we may want to add an (optional) mechanism to thread custom `http.Clients` in, currently applications could achieve something similar by configuring `http.DefaultClient`.
Fixes #516

Move witnessing fully into lifecycle layer

---

README.md
README_test.go

Improved docs primarily for appender and migrate lifecycle modes.
Towards #574.

[Docs] Improve docs for common lifecycles

---

append_lifecycle.go
lifecycle.go
migrate_lifecycle.go
otel.go
storage/aws/antispam/aws.go
storage/aws/antispam/aws_test.go
storage/gcp/antispam/gcp.go
storage/gcp/antispam/gcp_test.go

This PR adds a couple of `Follower`-related metrics:
* Position (by follower name): which exposes the highest index each follower has consumed.
* Lag (by follower name): how many entries behind the currently integrated tree each follower each follower is.
Towards #570

Add follower metrics

---

cmd/conformance/gcp/otel.go
go.mod

This PR adds automatic resource attribute detection for the GCP conformance binary.
Note that this PR will cause the namespace of metrics to change, so any dashboards will need updating.
Towards #570

GCP Add OTel automatic resource detection

---

cmd/conformance/aws/main.go

This PR tweaks some tunables to lower write-latency for the conformance/CI use-case.
Previously, we were waiting for a full second for a batch of 1024 entries which was never going to arrive.

[AWS] Tune conformance binary for lower latency

---

cmd/conformance/gcp/main.go

This PR tweaks some tunables to lower write-latency for the conformance/CI use-case.
Previously, we were waiting for a full second for a batch of `1024` entries which was never going to arrive.

[GCP] Tune conformance for lower latency

---

cmd/conformance/aws/main.go
deployment/live/aws/codelab/README.md
deployment/live/aws/conformance/terragrunt.hcl
deployment/modules/aws/codelab/main.tf
deployment/modules/aws/codelab/outputs.tf
deployment/modules/aws/codelab/variables.tf
deployment/modules/aws/conformance/main.tf
deployment/modules/aws/conformance/variables.tf
deployment/modules/aws/storage/main.tf
deployment/modules/aws/storage/variables.tf
storage/aws/antispam/aws.go

Antispam DB can now be created via the Terraform, and the conformance
command takes flags that allow antispam to be enabled and configured
with this DB.
Docs have been added to the end of the codelab instructions to document
how to deploy this.
Some performance testing was performed and results look good: with 1200
write workers doing 1200 writes per second, with 30% dupe chance, the
log was keeping up, growing by around 800 leaves per second.
```
Read (8 workers): Current max: 20/s. Oversupply in last second: 0
Write (1200 workers): Current max: 1200/s. Oversupply in last second: 0
TreeSize: 199416 (Δ 745qps over 30s)
Time-in-queue: 6ms/411ms/1056ms (min/avg/max)
Observed-time-to-integrate: 43ms/1291ms/4346ms (min/avg/max)
```
There are a couple of fixes in here for state/transaction …

[AWS Antispam] End-to-end antispam for conformance

---

deployment/live/aws/conformance/ci/terragrunt.hcl
deployment/live/aws/conformance/terragrunt.hcl
deployment/modules/aws/conformance/main.tf
deployment/modules/aws/conformance/variables.tf
deployment/modules/aws/storage/main.tf

This is failing at the moment since being enabled in #592. Some permissions need to be fixed, but disabling this to avoid other breakages in the meantime.

Disable antispam in AWS CI

---

append_lifecycle.go
lifecycle.go
storage/aws/aws.go
storage/gcp/gcp.go
storage/mysql/mysql.go
storage/posix/files.go

This PR adds a metric which exposes the next index which will be used for sequencing.
Such a metric helps determine whether a log is fully drained, critical information when switching lifecycle modes. 
Towards #588

Add NextIndex metric

---

cmd/conformance/aws/main.go
cmd/conformance/gcp/main.go
storage/aws/antispam/aws.go
storage/gcp/antispam/gcp.go

This PR adjusts defaults for the antispam implementations.
The new numbers come from running the GCP implementation at scale for a while. AWS has been _optimistically_ bumped to match as implementation is similar, but should be revisited once more experience is gained with it.

Adjust antispam defaults, and use them in conformance bins

---

storage/aws/antispam/aws.go
storage/gcp/antispam/gcp.go
storage/internal/stream.go
storage/posix/antispam/badger.go

This PR factors out the common implementation of `entryReader` next to `StreamAdaptor`.
In general, we're not at the point where we want to start factoring things out of storage implementations, but this one (which is specific to antispam, as opposed to log storage) is slightly different - the implementation of `entryStreamReader` is intricate, and is intended for use with the output of the `StreamAdaptor` implementation in the same package.
There's further work which could be done here, but that's for later.

Factor-out EntryStreamReader

---

storage/posix/antispam/badger.go

This PR changes the encoding of the hash used to key the Badger-based POSIX antispam DB to use BigEndian.
This is really just to keep it the same as other encodings we do in here (e.g. all the C2SP encodings are BigEndian), it doesn't _really_ matter as it's entirely internal, but consistency is nice.

Use BigEndian in badger

---

storage/posix/README.md
storage/posix/files.go

This PR removes support for idempotent writes from the POSIX storage driver implementation.
During normal operation, the only `tlog-tiles` resource which can ever be overwritten is `/checkpoint`; tiles and entry bundle resources are never appended to nor overwritten.
The POSIX driver does *synchronous integration* at the point of queue flush. If there were an error/the binary crashes during this flush/integration process, all flushed `Add` calls contributing to the integration batch will return an error (or, in the case of a crash, will never return), and no new `checkpoint` is created.
Since no knowledge of indices assigned is passed to the caller, nor is any commitment is made to any state updated, any "detritus" left by an errored integration run is both *ephemeral* and *not implied* …

[POSIX] Drop idempotent writes

---

docs/performance.md
storage/posix/PERFORMANCE.md

This PR updates the POSIX performance numbers to reflect how things currently stand with the recent changes to add antispam and `fsync`.

Update POSIX perf docs

---

client/client.go
client/client_test.go
integration/integration_test.go
internal/witness/witness.go

This PR makes `NewProofBuilder` require only a tree size, rather than a full `checkpoint`.
This is safe as generated proofs must be verified against checkpoint root hashes by the consumer anyway; any inconsistency will be detected at that point, and brings it into line with most other proof building implementations (Trillian, GoSumDB, tlog, etc.)
The change provides a means to construct consistency proofs without having to hold both checkpoints (e.g. if you're trying to convince someone else of consistency between a checkpoint they hold, and a newer checkpoint you hold - this is exactly what happens during the tlog-witness protocol).

NewProofBuilder operates in terms of tree size

---

append_lifecycle.go

This PR provides what's intended to be a temporary mechanism to enable logs to interact with the witness network in a _fail open_ fashion, whereby they will publish checkpoints & whatever valid witness signatures were obtained for it, regardless of whether the obtained signatures satisfy the specified witness policy.
With this option enabled logs and their clients can start to interact with the witness network in a safe "fail open" fashion as it develops and matures.

Allow witness signature collection to fail open

---

client/fetcher.go

Here is the Go Playground code to show how the existing non-wrapped error does not fit into the contract.
https://go.dev/play/p/WVZ2oLE5Zxm

Fix missing wrapped `os.ErrNotExist` for `http.StatusNotFound` case in `HTTPFetcher`

---

cmd/experimental/fsck/README.md
cmd/experimental/fsck/main.go
internal/fsck/fsck.go
internal/stream/otel.go
internal/stream/stream.go
storage/aws/antispam/aws.go
storage/aws/aws.go
storage/gcp/antispam/gcp.go
storage/gcp/gcp.go
storage/posix/antispam/badger.go
storage/posix/files.go

This PR adds a simple `fsck` tool for `tlog-tile` compatible logs.
It recalculates the root hash in a `checkpoint` by reading all entry bundles implied by the checkpoint, verifies that all tiles implied by the checkpoint are present and contain the hashes the should, and that the checkpoint's root hash matches the calculated value.

Add a simple tlog-files fsck tool

---

storage/aws/README.md
storage/aws/aws.go
storage/aws/aws_test.go
storage/gcp/README.md
storage/gcp/gcp.go
storage/gcp/gcp_test.go

This PR fixes the issue where a log with multiple concurrently running binaries may rarely encounter a situation where more than one binary attempts to publish a new checkpoint at the same time.
While this cannot cause an integrity issue since the tree is already integrated, and all but one of the concurrent attempts will ultimately fail, it _could_ cause a little bit of extra load on witnesses and so should be avoided.

Prevent multiple concurrent checkpoint update attempts in GCP and AWS

---

storage/gcp/gcp.go

similar to #497 - we should ensure the errors from some calls in a `ReadWriteTransaction` are wrapped to enable retry logic; `ReadOnlyTransactions` never abort so i think only these are needed
@AlCutter fyi

bubble up abort other spanner errors to enable retries

---

storage/aws/aws.go
storage/aws/aws_test.go
storage/gcp/gcp.go
storage/gcp/gcp_test.go

This PR fixes a bug in the checkpoint publication code for GCP and AWS where the last published time was erroneously updated even if no checkpoint was published. If the publication attempts happened more frequently that the minimum publish interval, this resulted in no checkpoints being published.
Now the last published time is only updated if the checkpoint is updated, and tests updated to catch this case.

Fix checkpoint publish in AWS & GCP

---

internal/fsck/fsck.go
internal/stream/follower.go
internal/stream/stream.go
lifecycle.go
storage/aws/antispam/aws.go
storage/aws/antispam/aws_test.go
storage/aws/aws.go
storage/aws/aws_test.go
storage/gcp/antispam/gcp.go
storage/gcp/antispam/gcp_test.go
storage/gcp/gcp.go
storage/gcp/gcp_test.go
storage/mysql/mysql.go
storage/mysql/mysql_test.go
storage/posix/antispam/badger.go
storage/posix/files.go

This PR makes the `stream` package a little simpler to use/reason about:
- `StreamAdaptor` now returns a Go iterator, and iterates only over the explicitly request range of entries (previously it would hang forever and return new entries if/when the tree grew)
- `EntryReader` is replaced with an iterator wrapper for `StreamAdaptor`

Simpler stream

---

internal/stream/follower.go
lifecycle.go

`NextIndex` was accidentally moved into `Streamer`, this PR moves it back to `LogReader`.

Correct LogReader interface

---

client/client.go
client/client_test.go

This PR makes the client fallback to fetching full tiles if an expected partial tile is not found. This is necessary since logs are permitted to remove partial tiles & entrybundles once the corresponding full resource has been published.
Towards #671.

Make client code fallback to requesting full tiles

---

internal/hammer/hammer.go

https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Retry-After

Fix missing `-` from `Retry-After` header in hammer

---

go.mod
migrate.go

This PR changes the backoff/retry library we use over to the `centkali` one, in order to try to standardise on the same one in a few related codebases.

Switch to using centkalti for retry logic

---

append_lifecycle.go
append_lifecycle_test.go
client/stream_test.go

This PR ensures that repeated calls to the future returned by `NewAppender` are idempotent.

Memoize the outer-most AddFn

---

README_test.go
cmd/conformance/posix/main.go
cmd/examples/posix-oneshot/main.go
cmd/experimental/migrate/posix/main.go
internal/witness/witness_test.go
storage/aws/aws.go
storage/gcp/gcp.go
storage/gcp/gcp_test.go
storage/posix/files.go
storage/posix/files_test.go
testonly/testlog.go

This PR allows applications using Tessera to (optionally) pass pre-configured instances of infrastructure clients to the drivers, enabling applications to tune those clients to the intended usage patterns and environment (e.g. https://pkg.go.dev/google.golang.org/api/option).
In this PR, we also make `posix.New` take a `Config` struct, as in the `gcp` and `aws` packages to both improve ergonomics when switching between backends, and to open the door to adding future config options to POSIX in a backwards-compatible manner.

Allow application to optionally configure storage infra clients

---

await.go
await_test.go

This PR makes the `PublicationAwaiter` more concise by using a `sync.Cond` so that calls to `Await()` are notified to check and release themselves when an updated checkpoint is seen, rather than relying on managing many channels.
This happens to also reduce memory usage & allocs by around 30% but isn't a strong driver.

Simplify PublicationAwaiter

---

storage/posix/file_ops.go

This PR avoids an error if two routines end up racing to create a directory.
POSIX mkdir is atomic, so no need to try to sort this out with mutexes.

Don't complain if dir already exists

---

storage/internal/queue.go

Calling notify where there was an error that had prevented sequencing was causing a panic, as reported in #731. This change still panics if no index and no error is provided, but now properly notifies if an error is provided without an index.

Support errors in notify

---

storage/internal/queue_test.go

Tested what happens when errors are provided with no index being set. I wanted to test the panic case, but it's gnarly because it happens in a goroutine we don't spawn, so we can't recover from it in the test.

Added tests for #734

---

cmd/fsck/main.go
fsck/fsck.go

This PR fixes a couple of short-comings of the `fsck` tool:
- Allows it to work with `file://` URLs
- Addresses an error when it's asked to check an empty tree

Improvements to the fsck tool

---

.github/workflows/integration_test.yml
go.mod
go.sum
integration/fault/posix/fault_test.go

This PR adds a fault-injection test for POSIX, using `strace` and `posix-oneshot` to try to cause tree corruption on disk.

Add fault-injection test for posix-oneshot

---

internal/witness/witness_test.go
witness.go
witness_test.go

This PR removes the assumption in the code that witnesses are always contacted via bastions.
Witnesses are now contacted directly on the URLs provided - if a witness is only contactable via a bastion, then the user must provide the URL on that bastion at which the witness is reachable.

Fix witness URL used for checkpoint for submission

---

witness.go
witness_policy_test.go

Use a simple `[]byte` to pass the policy in, there's not much benefit to using an `io.Reader` as the policy is tiny.

Pass witness policy as []byte

---

storage/gcp/antispam/gcp.go
storage/gcp/antispam/gcp_test.go

This PR causes the GCP `antispam` to detect if it's running under the Spanner emulator, and automatically apply the workaround for the lack of parallel transaction support in the emulator.
While this isn't a supported production environment, this enables local testing envs to be spun up using the emulator while still supporting antispam.

Detect emulated spanner and apply workaround

---

cmd/fsck/tui/fsck_panel.go
cmd/fsck/tui/stats_view.go
fsck/fsck.go
fsck/fsck_test.go

This PR adds another line to the fsck TUI, showing the total and avg throughput (bytes, resources, and errors) along with an ETA.

Add throughput and ETA stats to fsck UI

---

append_lifecycle.go
log.go
storage/aws/antispam/aws.go
storage/aws/aws.go
storage/gcp/antispam/gcp.go
storage/gcp/gcp.go
storage/posix/antispam/badger.go

This allows clients to tell various pushback errors apart, which can be useful for further processing.

More specific pushback errors

---

cmd/examples/posix-oneshot/README.md

Set the "LOG_DIR" var (already used in the example script) to a simple dummy value which is likely to work, so that the example script as a whole now fully runs with no modification needed.
(Every other detail was already fully copy-pasta friendly -- well done and thank you, author of that! -- so I thought I'd put on the finishing touch.)

fix missing env var in example in readme
