storage/gcp/DESIGN.md
This PR adds a short design overview of how the GCP storage is intended to work.
Fixes #17
Towards #23
=> Add high level GCP design doc

cmd/example-mysql/main.go, storage/mysql/mysql.go, storage/mysql/schema.sql
https://github.com/transparency-dev/trillian-tessera/issues/21
=> Add read tile in MySQL storage implementation

cmd/example-mysql/main.go, cmd/example-mysql/main_test.go
=> Fix incorrect `parseTileLevelIndexWidth` implementation and add tests

storage/mysql/DESIGN.md
=> Add high level MySQL design doc

storage/gcp/gcp.go, storage/gcp/gcp_test.go
This PR updates the GCP storage implementation to use the newly added formats and layouts.
Toward #23
=> Use Tessera formats

cmd/example-mysql/main.go, storage/mysql/mysql.go, storage/mysql/schema.sql
=> Add read entry bundles in MySQL storage implementation

cmd/example-gcp/main.go, entry.go, entry_test.go, storage/gcp/gcp.go, storage/gcp/gcp_test.go, storage/integrate.go, storage/integrate_test.go, storage/queue.go, storage/queue_test.go
This PR threads `tessera.Entry` through the mixins and into the GCP implementation.
Toward #23 #6 #8
=> Thread tessera.Entry through

client/client_test.go, testdata/build_log.sh, testdata/log/checkpoint, testdata/log/checkpoint.0, testdata/log/checkpoint.1, testdata/log/checkpoint.10, testdata/log/checkpoint.11, testdata/log/checkpoint.12, testdata/log/checkpoint.13, testdata/log/checkpoint.14, testdata/log/checkpoint.15, testdata/log/checkpoint.2, testdata/log/checkpoint.3, testdata/log/checkpoint.4, testdata/log/checkpoint.5, testdata/log/checkpoint.6, testdata/log/checkpoint.7, testdata/log/checkpoint.8, testdata/log/checkpoint.9
This involved regenerating the keys as the origin is tied to the signing name now.
=> Updated test data with more realistic origin

cmd/example-posix/main.go
=> Removed the origin flag

cmd/example-mysql/main.go, storage/mysql/mysql.go
=> Add TODOs to handle partial tile scenarios in MySQL storage implementation

storage/posix/DESIGN.md
This PR adds an overview of the POSIX storage implementation.
Toward #16 #22
=> POSIX design overview doc

cmd/example-mysql/docker/compose.yaml
This gives some indication of progress as integration events occur
=> Run example-mysql with added verbosity

hammer/client.go
Probably not really useful for load testing, but a small amount of code to check that the posix log is generating conformant logs
=> Add support for file-system logs

hammer/hammer.go, hammer/tui.go
This is just moving code around for clearer separation and documentation
via method naming.
=> Hammer: refactor for clearer separation

hammer/hammer.go
This moves instantiation of the leaf generation rules to the main function, which makes future work to support generating different types of leaves (e.g. x509 certs) easier to implement. Probability of duplicates has been moved to a flag, and some minor code inlining makes code better co-located.
=> Refactor leaf generation

hammer/hammer.go, hammer/tui.go
This makes it a bit more readable now, but really sets this up to grow in a way that doesn't turn into one enormous method with all of the UI logic in it.
=> Refactor TUI to separate setup and runtime controls

hammer/README.md
This provides a mile-high view of the intended design and usage in an
attempt to guide new maintainers.
Fixes #20
=> Write up basic hammer design

cmd/example-mysql/README.md
=> Add "How to Run a Tessera Log (MySQL)"

personalities/sctfe/handlers.go
=> return Add error messages

cmd/example-posix/README.md, cmd/example-posix/main.go
This makes this example consistent in API with the other examples, and allows the implementation to be load tested via the hammer
=> example-posix brings up an HTTP POST /add handler

personalities/sctfe/handlers.go
=> Forward Tessera pushbacks to clients

personalities/sctfe/handlers.go, personalities/sctfe/handlers_test.go
Towards #88 
Removed it by mistake in #105
=> (Re)Add get-roots endpoint

cmd/example-mysql/main.go, integration/example-mysql/integration_test.go
=> Fix incorrect entry index in example-mysql

.github/workflows/integration_test.yml, integration/integration_test.go
Note that the HTTP client timeout is bumped to 60 seconds to avoid timeout from posix integration test.
=> Add POSIX integration test

docs/design/README.md
This PR adds a bit more detail to `docs/design/README.md`.
Towards #4 & #9
=> Flesh out design readme a bit

cmd/conformance/posix/README.md, cmd/conformance/posix/main.go
Makes the core business logic more front and centre.
=> posix conformance: small refactor and improved docs

cmd/conformance/mysql/main.go
The flow of the main method is now more focused on the Tessera logic instead of DB & verifier/signer logic.
=> MySQL conformance: refactor main method for readability

hammer/client.go, integration/integration_test.go
The fixes the fixup in #206. Once and for all.
=> Make the test really fail when it fails

cmd/conformance/mysql/docker/Dockerfile
=> Fix `FromAsCasing` warning from MySQL's Dockerfile

cmd/conformance/mysql/README.md
=> Update mysql Docker image to 8.4 in MySQL README

docs/design/lifecycle.md
These are the states we considered when designing Tessera, and the state transitions we have explicitly designed for. Fixes #14.
=> Defined the lifecycle states

hammer/Dockerfile
This PR adds a simple Dockerfile for building the hammer tool.
=> Add Dockerfile for hammer

README.md
=> Add `posix-oneshot` to README

deployment/live/gcp/cloudbuild/README.md, deployment/live/gcp/cloudbuild/prod/terragrunt.hcl, deployment/live/gcp/cloudbuild/terragrunt.hcl, deployment/live/gcp/conformance/README.md, deployment/live/gcp/conformance/terragrunt.hcl, deployment/modules/gcp/cloudbuild/main.tf, deployment/modules/gcp/cloudbuild/outputs.tf, deployment/modules/gcp/cloudbuild/variables.tf, deployment/modules/gcp/conformance/main.tf, deployment/modules/gcp/conformance/outputs.tf, deployment/modules/gcp/conformance/variables.tf, deployment/modules/gcp/gcs/main.tf, deployment/modules/gcp/gcs/variables.tf
This PR adds a first cut at terraform to manage conformance testing on GCP.
Towards #8
=> [GCP] conformance terraform 

.github/workflows/generated_files.yml
Fixes https://github.com/transparency-dev/trillian-tessera/security/code-scanning/3
=> Fix pinned dependencies code scanning alert

.github/workflows/codeql.yml
Just realised I've pushed the branch to transparency-dev org. I will remove the branch after this pull request is merged.
=> Add CodeQL GitHub workflow

.github/workflows/terragrunt_test.yml
Fixes https://github.com/transparency-dev/trillian-tessera/security/code-scanning/4
=> Fix token permission code scanning alert

storage/mysql/mysql.go
Fixes https://github.com/roger2hk/trillian-tessera/security/code-scanning/10.
=> Fix incorrect conversion between integer types code scanning alert

api/layout/example_test.go
=> Add godoc examples for layout package

docs/performance.md
=> Add tl;dr to Tessera Storage Performance doc for MySQL

client/client.go
This commit preallocates slices of hashes in a couple of places. As a drive-by, it makes the hashes slice naming and append style consistent.
=> Preallocate slices of hashes

api/layout/paths.go, api/state.go, client/client.go, ctonly/ct.go
A couple of hyperlinks and fixed a typo
=> Minor improvements to docs

internal/hammer/hammer.go, internal/hammer/workers.go
Also added a comment to the other usage of math/rand/v2 prompted by IRL
conversations about it.
=> Use math/rand/v2 to cleanup some nonsense

cmd/conformance/gcp/main.go, deployment/modules/gcp/cloudbuild/main.tf, deployment/modules/gcp/conformance/main.tf, deployment/modules/gcp/conformance/variables.tf, storage/mysql/mysql_test.go
=> delete unused verifier code

cmd/examples/posix-oneshot/main.go
This PR applies the synchronous integration mix-in (`Awaiter`) to the GCP one-shot example.
=> Use synchronous integration mix-in in one-shot tool

storage/posix/files.go
This mutex embedding meant that any personalities using this storage had the ability to Lock and Unlock, which was not an expected API option. This change makes it a private member, thus cleaning the API and making it a cleaner black box.
=> [POSIX] Tidy API: make mutex a field

README.md
Previously the docs for personality authors were essentially "go and
read the example code and figure it out". These docs have now been
expanded to provide an introduction to many useful concepts, and provide
a guide for how to start writing a personality.
This is not intended to be a final revision and it is likely that there
is a lot more content to add here in the coming months.
=> [README] Docs for personality authors

storage/aws/README.md
See the two stage commits.
Let's update the checkpoint logic in a followup PR or with #372 directly.
=> AWS Design doc.

cmd/conformance/aws/README.md
Hence removing `Work in progress, not ready to be used yet.`
=> align cmd/conformance/aws/README.md with gcp

client/client_test.go
This PR adds a regression test for #401
=> Add test for GetEntryBundle addressing

storage/aws/aws.go
Fixes https://github.com/transparency-dev/trillian-tessera/security/code-scanning/13.
=> Remove AWS `dsn` from error log to avoid password leak

.github/workflows/integration_test.yml, integration/integration_test.go, storage/posix/files.go
This PR fixes an issue in the POSIX backend which can result in missing entry bundles.
It also makes a couple of improvements to the integration test to help debugging these types of issue.
=> Fix POSIX full-bundle handling

README.md
Make sure there's always an easy to find link. #338.
=> Added link to benchmarks

.github/workflows/benchmark-go-main.yml, .github/workflows/benchmark-go-pr.yml, .github/workflows/codeql.yml, .github/workflows/scorecard.yml, .github/workflows/terragrunt_test.yml
Fixes the following code scanning alerts:
- https://github.com/transparency-dev/trillian-tessera/security/code-scanning/4
- https://github.com/transparency-dev/trillian-tessera/security/code-scanning/30
- https://github.com/transparency-dev/trillian-tessera/security/code-scanning/31
- https://github.com/transparency-dev/trillian-tessera/security/code-scanning/32
- https://github.com/transparency-dev/trillian-tessera/security/code-scanning/33
- https://github.com/transparency-dev/trillian-tessera/security/code-scanning/34
- https://github.com/transparency-dev/trillian-tessera/security/code-scanning/35
=> Fix token permission code scanning alerts

README.md
Also fixed some out of date docs around alpha and AWS
=> [Docs] Glanceable roadmap features in main README

storage/aws/aws.go
The version is written at schema creation, and checked on startup. If they are different, it fails. Towards #450.
=> [AWS] Check compatibility version of the DB schema on startup

internal/hammer/loadtest/analysis.go
=> Fix missing error message for errors occuring every second

internal/witness/witness.go, internal/witness/witness_test.go
This ensures that we always return a non-nil error if the policy was not satisfied, and adds some tests.
Towards #309
=> Basic validation of witness signatures

README.md, cmd/conformance/aws/main.go, cmd/conformance/gcp/main.go, cmd/conformance/mysql/main.go, cmd/conformance/posix/main.go, cmd/examples/posix-oneshot/main.go
Also rename mix-ins to features, as things have changed a bit and 2/3 of these features are discoverable via the top-level API instead of being optional libraries.
=> [Docs] Update code samples in docs

append_lifecycle.go, ct_only.go, migrate.go, witness.go
Duplicate docs instead of linking to private docs
=> Remove unused things from API

internal/witness/witness.go
This prevents a malicious witness from updating the log witness state to an invalid size that is larger than the log size.
=> Witnessing: Prevent the log from updating to an invalid size

cmd/conformance/gcp/main.go, cmd/experimental/migrate/gcp/main.go, storage/gcp/antispam/gcp.go
This PR exposes a couple of options to allow performance/throughput tuning for the GCP antispam implementation.
=> [GCP] Add antispam tunables

cmd/conformance/aws/main.go
Better than string formatting ourselves. Follows on from #541.
=> [AWS] Use library to create DNS string

storage/gcp/antispam/gcp.go
This PR removes the `id` column from the GCP antispam DB.
This column isn't necessary on this table.
This is a schema-breaking change, so any deployments using GCP antispam will need to have their anti-spam database instance recreated and repopulated.
=> Remove id column from IDSeq

docs/design/antispam.md
This PR adds a high-level design overview of Tessera's antispam mechanism.
#469 #155
=> Add antispam overview

append_lifecycle.go, storage/mysql/mysql.go
This PR adds metrics which offer insights into how integration is performing.
Towards #570
=> Add metrics around integration

README.md
Documentation for performing these actions. This fixes #574.
=> [Docs] Freezing/Deleting/Sharded logs

append_lifecycle.go
This PR causes `duplicate` and `pushback` attributes to always be present on adds count metric.
Previously, they were only added when they were going to be set to `true`, but this makes it hard to create graphs/alerts for conditions which haven't yet been seen by the monitoring infrastructure since the names of these attributes are unknown.
=> Set duplicate and pushback attributes on all add metric increments

README.md
=> Update freezing docs

dedupe.go, dedupe_test.go
This PR stops the `InMemoryDedup` struct from incorrectly caching errors from lower levels.
This behaviour is problematic as errors (which may include `ErrPushback`) are likely transient, and we shouldn't get in the way of users retrying the same request. The degenerate case is a single user retrying indefinitely with the same entry; if the first request gets an error (e.g. `ErrPushback`), they will never be able to resubmit the entry as without a flow of other entries being added to force an eviction from the cache, the user will always see the cached error response.
This PR has the cached future explicitly remove itself from the cache if it returns an error when it's resolved.
=> Don't cache errors in InMemoryDedup

storage/posix/file_ops.go, storage/posix/files.go
This PR adds calls to sync to ensure that written files/directories are durably stored on disk.
Towards #22
=> [POSIX] Ensure data is durably written to disk

.github/workflows/golangci-lint.yml
=> Bump linter

internal/hammer/loadtest/client.go, internal/witness/witness_test.go, witness.go
https://google.github.io/styleguide/go/decisions#initialisms
=> Replace all `Url` with `URL`

client/fetcher.go
https://google.github.io/styleguide/go/decisions#switch-and-break
=> Remove redundant `break`

append_lifecycle.go, internal/stream/follower.go, internal/stream/stream.go, lifecycle.go, migrate_lifecycle.go, storage/aws/antispam/aws.go, storage/gcp/antispam/gcp.go, storage/posix/antispam/badger.go
This moves one type that wasn't intended to be public away from public API.
=> Moved Follower into stream package

internal/migrate/migrate.go, migrate_lifecycle.go, storage/aws/aws.go, storage/gcp/gcp.go, storage/mysql/mysql.go, storage/posix/files.go
Hidden:
- UnbundlerFunc
- MigrationWriter
=> [API] More API tidying and hiding

storage/aws/README.md, storage/gcp/README.md
Add missing tables to AWS and GCP README files.
=> Update GCP/AWS READMEs with new table info

storage/internal/queue_test.go
Current performance:
```
BenchmarkQueue-12                    373           3098761 ns/op	1285665 B/op      28741 allocs/op
```
There's no evidence that this is problematic, but good to keep an eye on
the CPU and memory scores as I suspect they could be made cheaper if
needed; I took a quick look at the escape analysis from the compiler,
and we put a bunch of stuff on the heap for every new entry.
=> Added benchmark for queue

storage/aws/aws.go, storage/gcp/gcp.go, storage/mysql/mysql.go, storage/posix/files.go
This was too noisy in personality logs otherwise
=> [Logging] Integration logging is now V=1

storage/posix/antispam/badger.go
This PR fixes an issue where the POSIX antispam incorrectly busy-loops when it's caught up. It's not a correctness issue, but will needlessly consume CPU.
=> [POSIX/antispam] Don't busy wait when we're caught up

append_lifecycle.go
In https://github.com/sigstore/rekor-tiles/issues/434 it is reported that there are deadline exceeded errors. This could be Tessera taking longer than expected, or it could be clients calling this with unreasonably short deadlines. This histogram metric should give some insight into the spectrum of deadlines that clients are expecting Tessera to work with.
=> [Metrics] Histogram for deadline remaining on Append

deployment/live/aws/conformance/terragrunt.hcl
Towards #740.
Following https://opentofu.org/docs/language/settings/backends/s3/#s3-state-locking.
=> Disable DynamoDB Terraform locking

append_lifecycle.go, cmd/conformance/aws/main.go, cmd/conformance/gcp/main.go, cmd/conformance/mysql/main.go, cmd/conformance/posix/main.go
Provide some colour and guidance on params to pass to `WithAntispam`.
=> Add godoc for WithAntispam

deployment/modules/aws/storage/main.tf
Apply same fix from https://github.com/transparency-dev/tesseract/pull/532 to fix AWS CI issue.
Fixes #774
=> Fix AWS CI deploy issue
